// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2_0ZsczizrdSo2O3TOIV3W_8ZVViXkBI',
    appId: '1:819375233294:web:53e6cdba6cdbb8d1255f5f',
    messagingSenderId: '819375233294',
    projectId: 'eduvox2025',
    authDomain: 'eduvox2025.firebaseapp.com',
    storageBucket: 'eduvox2025.firebasestorage.app',
    measurementId: 'G-EKJ1T1TNSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3K4gydlhnHC3uiTUXocbXN14vWIPNCaM',
    appId: '1:819375233294:android:6b940cf407ccb152255f5f',
    messagingSenderId: '819375233294',
    projectId: 'eduvox2025',
    storageBucket: 'eduvox2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbsMy5Sfn9JEFcEG9tZcC9i3Gx6ikBQSw',
    appId: '1:819375233294:ios:dcb7e831513b4bb8255f5f',
    messagingSenderId: '819375233294',
    projectId: 'eduvox2025',
    storageBucket: 'eduvox2025.firebasestorage.app',
    iosClientId: '819375233294-90lejkt47tpp52jjdntahet1qjc6pn49.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduvox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbsMy5Sfn9JEFcEG9tZcC9i3Gx6ikBQSw',
    appId: '1:819375233294:ios:dcb7e831513b4bb8255f5f',
    messagingSenderId: '819375233294',
    projectId: 'eduvox2025',
    storageBucket: 'eduvox2025.firebasestorage.app',
    iosClientId: '819375233294-90lejkt47tpp52jjdntahet1qjc6pn49.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduvox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2_0ZsczizrdSo2O3TOIV3W_8ZVViXkBI',
    appId: '1:819375233294:web:68f60f697a6b70a0255f5f',
    messagingSenderId: '819375233294',
    projectId: 'eduvox2025',
    authDomain: 'eduvox2025.firebaseapp.com',
    storageBucket: 'eduvox2025.firebasestorage.app',
    measurementId: 'G-2YWXMWWDVY',
  );

}